project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!teaching/**/*.md"
    - "!teaching/**/*.Rmd"
  resources:
    - "cv/"

website:
  title: "S. Tanvir Hossain"
  description: "Academic personal website"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog

  page-footer:
    left: "© 2024 S. Tanvir Hossain. All rights reserved."
    right: "Built with [Quarto](https://quarto.org/)"


format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    toc: true
    page-layout: full
    html-math-method: mathjax
    mathjax:
      config:
        tex:
          inlineMath: [['$', '$'], ['\\(', '\\)']]
          displayMath: [['$$', '$$'], ['\\[', '\\]']]
        options:
          skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre']